version: '3.6'
services:
  api:
    build: .
    image: music-api
    restart: always
    ports:
      - 8000:8000
    environment:
      MYSQL_DATABASE: 'musicdb'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'musicdb'
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

volumes:
  mysql-data:
    name: proj-mysql-data
